### PR TITLE
Configure opendexd entrypoint

### PR DESCRIPTION
**Pull request by 3nprob**
* Allows default overriding existing paths and ports in opendexd entrypoint.sh
* Adds new variables:
  * `TOR_TORRC` sets path to torrc (though I guess this will go away in the future when it gets moved to its own container)
  * `LND_HOSTNAME_FILE` (see above should be removed with the above future changed)
  * `LNDLTC_DISABLE` to not enable/require LTC integration

Should retain existing defaults for all

### CODE REVIEW

**Review by Maith8Ae — CHANGES_REQUESTED** [review]
Is `setup.sh` file permission change (644 -> 755) required for this PR?

**Comment by 3nprob** [comment]
Forgot to mention that in the PR description - is there any reason it shouldn't be executable? (it's intended to be executed from bash after all)

**Comment by Maith8Ae** [comment]
> Forgot to mention that in the PR description - is there any reason it shouldn't be executable? (it's intended to be executed from bash after all)

@3nprob This file is [invoked by xud.sh in old xud-docker repo](https://github.com/ExchangeUnion/xud-docker/blob/2725ce89f0506123ebe998de22bf3fd3ce1e72a5/xud.sh#L45). But it's no longer used in opendex-docker. It's better to delete this file. BTW the `opendex.sh` will be used as a thin wrapper of the launcher providing the same streamline setup experience as `xud.sh`. The implementation of `opendex.sh` is in the near todo list.

**Comment by 3nprob** [comment]
Ah, got it - I can still run this fine without the launcher though right?

**Comment by 3nprob** [comment]
Added commit that removes `setup.sh`

**Review by Maith8Ae — APPROVED** [review]

**Comment by Maith8Ae** [comment]
> Ah, got it - I can still run this fine without the launcher though right?

Yes. It will bring up our last xud-docker release.

**Pull request merged**
